import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import ProfilePic from "../public/images/profile-picture.svg";
import LinkedinIcon from "../public/images/icons/linkedin.svg";
import BehanceIcon from "../public/images/icons/behance.svg";
import DribbleIcon from "../public/images/icons/dribble.svg";
import InstagramIcon from "../public/images/icons/instagram.svg";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="py-16">
        <div className="container">
          <div className="border-b border-custom flex items-center justify-center pb-16 max-sm:pb-8 max-sm:block ">
            <div className="max-sm:w-44 max-sm:h-44 w-52 h-52 border-4 border-white rounded-full text-center max-sm:mx-auto  ">
              <Image
                src={ProfilePic}
                alt="#"
                className="object-cover w-48 h-48 rounded-full max-sm:w-40 max-sm:h-40 "
                style={{ position: "relative", top: "4px", left: "4px" }}
              />
            </div>
            <div className="ml-16 max-sm:ml-0 max-sm:text-center max-sm:mt-4">
              <h3 className="text-5xl font-extrabold mb-3 max-sm:mb-2 max-sm:text-4xl">
                Nur Farhad
              </h3>
              <p className="text-xl font-medium max-sm:text-lg">
                Next Gen Designer
              </p>
              <div className="mt-5 max-sm:mt-4">
                <ul className="inline ">
                  <li className="inline-block mr-3">
                    <a href="#" target="_blank">
                      <Image
                        src={LinkedinIcon}
                        alt="#"
                        className="object-contain w-8 h-8 max-sm:w-6 max-sm:h-6"
                      />
                    </a>
                  </li>
                  <li className="inline-block mr-3">
                    <a href="#" target="_blank">
                      <Image
                        src={BehanceIcon}
                        alt="#"
                        className="object-contain w-8 h-8 max-sm:w-6 max-sm:h-6"
                      />
                    </a>
                  </li>
                  <li className="inline-block mr-3">
                    <a href="#" target="_blank">
                      <Image
                        src={DribbleIcon}
                        alt="#"
                        className="object-contain w-8 h-8 max-sm:w-6 max-sm:h-6"
                      />
                    </a>
                  </li>
                  <li className="inline-block">
                    <a href="#" target="_blank">
                      <Image
                        src={InstagramIcon}
                        alt="#"
                        className="object-contain w-8 h-8 max-sm:w-6 max-sm:h-6"
                      />
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
